/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.karyawan;

import com.config.pojoKaryawan;
import com.config.table;
import com.controllers.karyawan;
import com.view.main.MainForm;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Programmer JUJU
 */
public class view extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    karyawan karyawanCtrl = new karyawan();
    String params = "";
    String[] id;
    com.view.karyawan.add addKaryawan;
    com.view.karyawan.edit editKaryawan;
    String nama, telp, uid, nik, alamat;

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        hide3Button();
    }

    private void initTable() {
        table tbl = new table();
        String kolom[] = {"No", "NIK", "Nama Karyawan", "No Telp / HP", "alamat"};
        boolean edit[] = {false, false, false, false, false};
        model = tbl.tabel(kolom, edit);
        tblKaryawan.setModel(model);
        tblKaryawan.getColumnModel().getColumn(0).setMaxWidth(45);
        tblKaryawan.getColumnModel().getColumn(1).setMaxWidth(225);
        tblKaryawan.setShowGrid(true);
    }

    private void fillTable() throws IOException, PropertyVetoException {
        initTable();
        String[] data = new String[5];
        int no=1;
        try {
            id = new String[100];
            pojoKaryawan rs = karyawanCtrl.view(params, 0, "nama", 0, 100);
            for(int i=0;i<rs.getLength();i++){
                id[i] = String.valueOf(rs.getId(i));
                data[0] = "" + no++;
                data[1] = rs.getNik(i);
                data[2] = rs.getNama(i);
                data[3] = rs.getTelp(i);
                data[4] = rs.getAlamat(i);
                model.addRow(data);
            }
//            while (rs.next()) {
//                id[no] = rs.getString("uid");
//                no++;
//                data[0] = "" + no;
//                data[1] = rs.getString("nik");
//                data[2] = rs.getString("nama");
//                data[3] = rs.getString("telp");
//                data[4] = rs.getString("alamat");
//                model.addRow(data);
//            }
        } catch (SQLException | IOException | PropertyVetoException ec) {
            System.out.println(ec);
            JOptionPane.showMessageDialog(this, "Gagal Mengambil Data", "Database Error", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("View Data Karyawan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter Data"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Filter Dengan Nama / NIK");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtCari)
                .addContainerGap())
        );

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        btnAdd.setText("TAMBAH");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("HAPUS");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("UBAH");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("BATAL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(510, 510, 510))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        // TODO add your handling code here:
        show3Button();
        int row = tblKaryawan.getSelectedRow();
        if (tblKaryawan.getSelectedColumnCount() == 1) {
            uid = id[row];
            nik = tblKaryawan.getValueAt(row, 1).toString();
            nama = tblKaryawan.getValueAt(row, 2).toString();
            telp = tblKaryawan.getValueAt(row, 3).toString();
            alamat = tblKaryawan.getValueAt(row, 4).toString();
        }

    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        try {
            // TODO add your handling code here:
            hide3Button();
            fillTable();
        } catch (IOException | PropertyVetoException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            // TODO add your handling code here:
            hide3Button();
            fillTable();
            //                btnAdd.setVisible(false);
        } catch (IOException | PropertyVetoException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            if (!addKaryawan.isVisible()) {
                MainForm.desktopPane.add(addKaryawan);
                addKaryawan.setVisible(true);
            }
        } catch (Exception ak) {
            addKaryawan = new add();
            MainForm.desktopPane.add(addKaryawan);
            addKaryawan.setVisible(true);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Apakah anda akan merubah data \n" + " \"" + nama + "\"", "Konfirmasi", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                if (!editKaryawan.isVisible()) {
                    MainForm.desktopPane.add(editKaryawan);
                    editKaryawan.setVisible(true);
                    edit.uid = Integer.valueOf(uid);
                    edit.txtNik.setText(nik);
                    edit.txtNama.setText(nama);
                    edit.txtTelp.setText(telp);
                    edit.txtAlamat.setText(alamat);
                }
            } catch (Exception ak) {
                editKaryawan = new edit();
                MainForm.desktopPane.add(editKaryawan);
                editKaryawan.setVisible(true);
                edit.uid = Integer.valueOf(uid);
                edit.txtNik.setText(nik);
                edit.txtNama.setText(nama);
                edit.txtTelp.setText(telp);
                edit.txtAlamat.setText(alamat);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        try {
            // TODO add your handling code here:
            if (!"".equals(txtCari.getText())) {
                params = txtCari.getText();
            } else {
                params = "";
            }
            fillTable();
        } catch (IOException | PropertyVetoException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        try {
            // TODO add your handling code here:
            hide3Button();
            fillTable();
        } catch (IOException | PropertyVetoException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameIconified

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        boolean delete = false;
        if (JOptionPane.showConfirmDialog(this, "Apakah anda akan merubah data \n" + " \"" + nama + "\"", "Konfirmasi", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                delete = karyawanCtrl.deleteKaryawan(Integer.valueOf(uid));
            } catch (SQLException | IOException | PropertyVetoException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (delete == true) {
                try {
                    JOptionPane.showMessageDialog(this, "Data \"" + nama + "\" Berhasil Dihapus", "Info", 1);
                    hide3Button();
                    fillTable();
                } catch (IOException | PropertyVetoException ex) {
                    Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void hide3Button() {
        txtCari.setText("");
        btnEdit.setVisible(false);
        btnCancel.setVisible(false);
        btnDelete.setVisible(false);
        btnAdd.setEnabled(true);
    }

    private void show3Button() {
        btnEdit.setVisible(true);
        btnCancel.setVisible(true);
        btnDelete.setVisible(true);
        btnAdd.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
