/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.main;

import com.view.karyawan.*;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer JUJU
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    com.view.karyawan.view viewKaryawan;
    com.view.karyawan.add addKaryawan;

    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        desktopPane.setUI(null);
        //Rectangle size =.getBounds();
        desktopPane.setBackground(java.awt.Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        deleteMenuItem = new javax.swing.JMenuItem();
        dataMenu = new javax.swing.JMenu();
        menuKaryawan = new javax.swing.JMenu();
        karyawanAdd = new javax.swing.JMenuItem();
        karyawanView = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simple App. With Pool Datasource");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setOpaque(false);

        editMenu.setMnemonic('e');
        editMenu.setText("File");

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Quit App");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        dataMenu.setMnemonic('D');
        dataMenu.setText("Data");

        menuKaryawan.setMnemonic('k');
        menuKaryawan.setText("Karyawan");

        karyawanAdd.setMnemonic('n');
        karyawanAdd.setText("Add New");
        karyawanAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanAddActionPerformed(evt);
            }
        });
        menuKaryawan.add(karyawanAdd);

        karyawanView.setMnemonic('v');
        karyawanView.setText("View ");
        karyawanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanViewActionPerformed(evt);
            }
        });
        menuKaryawan.add(karyawanView);

        dataMenu.add(menuKaryawan);

        menuBar.add(dataMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(840, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Tutup Aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Tutup Aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void karyawanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanViewActionPerformed
        // TODO add your handling code here:
        try {
            if (viewKaryawan.isVisible() == false) {
                desktopPane.add(viewKaryawan);
                viewKaryawan.setVisible(true);
            }
        } catch (Exception vk) {
            viewKaryawan = new view();
            desktopPane.add(viewKaryawan);
            viewKaryawan.setVisible(true);
        }
    }//GEN-LAST:event_karyawanViewActionPerformed

    private void karyawanAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanAddActionPerformed
        // TODO add your handling code here:
        try {
            if (!addKaryawan.isVisible()) {
                desktopPane.add(addKaryawan);
                addKaryawan.setVisible(true);
            }
        } catch (Exception ak) {
            addKaryawan = new add();
            desktopPane.add(addKaryawan);
            addKaryawan.setVisible(true);
        }
    }//GEN-LAST:event_karyawanAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu dataMenu;
    private javax.swing.JMenuItem deleteMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem karyawanAdd;
    private javax.swing.JMenuItem karyawanView;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuKaryawan;
    // End of variables declaration//GEN-END:variables
}
